export default {
  login: () => '/login',
  register: () => '/register',
  home: () => '/',
  profile: () => '/profile',
  planning: () => '/verification-planning',
  analytics: () => '/analytics',
  productionAnalytics: () => '/production-analytics',
  import: () => '/import',
  sqlConsole: () => '/sql-console',
  chat: () => '/chat',
  budget: () => '/budget-planning',
  // about: () => '/about/licenses',
  admin: {
    root: () => '/admin',
    users: () => '/admin/users',
    createUser: () => '/admin/users/create',
    editUser: (userId: string | ':userId') => `/admin/users/${userId}/edit`,
    cities: () => '/admin/cities',
    editCity: (cityId: string | ':cityId') => `/admin/cities/${cityId}/edit`,
    createCity: () => '/admin/cities/create',
    companies: () => '/admin/companies',
    editCompany: (companyId: string | ':companyId') =>
      `/admin/companies/${companyId}/edit`,
    createCompany: () => '/admin/companies/create',
    productionSites: () => '/admin/production-sites',
    editProductionSite: (productionSiteId: string | ':productionSiteId') =>
      `/admin/production-sites/${productionSiteId}/edit`,
    createProductionSite: () => '/admin/production-sites/create',
    equipmentTypes: () => '/admin/equipment-types',
    createEquipmentType: () => '/admin/equipment-types/create',
    editEquipmentType: (equipmentTypeId: string | ':equipmentTypeId') =>
      `/admin/equipment-types/${equipmentTypeId}/edit`,
    measurementTypes: () => '/admin/measurement-types',
    createMeasurementType: () => '/admin/measurement-types/create',
    metrologyControlTypes: () => '/admin/metrology-control-types',
    createMetrologyControlType: () => '/admin/metrology-control-types/create',
    scopes: () => '/admin/scopes',
    createScope: () => '/admin/scopes/create',
    primaryStandarts: () => '/admin/primary-standarts',
    createPrimaryStandart: () => '/admin/primary-standarts/create',
    statuses: () => '/admin/statuses',
    createStatus: () => '/admin/statuses/create',
    verificationOrganizations: () => '/admin/verification-organizations',
    createVerificationOrganization: () =>
      '/admin/verification-organizations/create',
    auditLogs: () => '/admin/audit-logs',
  },
};
