query GetInspectionPool($targetMonth: String!, $limit: Int!, $offset: Int!) {
  getInspectionPoolByMonth(
    targetMonth: $targetMonth
    limit: $limit
    offset: $offset
  ) {
    items {
      id
      name
      model
      serialNumber
      lastInspectionDate
      validUntil
      isOverdue
      controlType
    }
    totalCount
    #yearlySummary {
    #month
    # autoCount
    #manualCount
    #}
  }
}

query GetInspectionArchive($limit: Int!, $offset: Int!, $year: Int!) {
  getInspectionBatchesArchive(limit: $limit, offset: $offset, year: $year) {
    items {
      id
      number
      date
      comment
      createdBy {
        id
        role
        firstName
        lastName
      }
      devicesToBatches {
        id
        deviceStatus
        device {
          id
          name
          model
          serialNumber
        }
      }
    }
    totalCount
  }
}

query GetInspectionCalendarSummary {
  getInspectionCalendarSummary {
    month
    autoCount
    manualCount
  }
}

mutation CreateBulkInspection($items: [InspectionItemInput!]!) {
  createBulkInspection(items: $items)
}
